# Generated by Django 4.2.14 on 2025-06-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prevcad", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textrecomendation",
            name="quote_link",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
