# Generated by Django 4.2.14 on 2025-06-18 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("prevcad", "0002_alter_textrecomendation_quote_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255, verbose_name="Acción")),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha y hora"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Actividad de la Aplicación",
                "verbose_name_plural": "Registros de Actividad de la Aplicación",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="prevcad_app_timesta_78b365_idx"
                    ),
                    models.Index(
                        fields=["user"], name="prevcad_app_user_id_a6a2ca_idx"
                    ),
                ],
            },
        ),
    ]
