# Generated by Django 4.2.14 on 2025-06-25 20:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("prevcad", "0003_appactivitylog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appactivitylog",
            options={
                "ordering": ["-date"],
                "verbose_name": "Registro de Actividad de la Aplicación",
                "verbose_name_plural": "Registros de Actividad de la Aplicación",
            },
        ),
        migrations.RemoveIndex(
            model_name="appactivitylog",
            name="prevcad_app_timesta_78b365_idx",
        ),
        migrations.RemoveField(
            model_name="appactivitylog",
            name="action",
        ),
        migrations.RemoveField(
            model_name="appactivitylog",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="appactivitylog",
            name="actions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Registro de acciones realizadas por el usuario con timestamp, en formato JSON. Ejemplo{'08:02:33': 'Login', '08:02:35': 'Logout'}",
                verbose_name="Acciones",
            ),
        ),
        migrations.AddField(
            model_name="appactivitylog",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appactivitylog",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Fecha de la actividad registrada",
                verbose_name="Fecha",
            ),
        ),
        migrations.AddField(
            model_name="appactivitylog",
            name="n_entries",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Número de Entradas"
            ),
        ),
        migrations.AddField(
            model_name="appactivitylog",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="appactivitylog",
            index=models.Index(fields=["date"], name="prevcad_app_date_5293ce_idx"),
        ),
    ]
