# Generated by Django 4.2.14 on 2025-06-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prevcad", "0004_alter_appactivitylog_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appactivitylog",
            options={
                "ordering": ["-date"],
                "verbose_name": "Registro de Actividad en la Aplicación",
                "verbose_name_plural": "Registros de Actividad en la Aplicación",
            },
        ),
        migrations.AddField(
            model_name="appactivitylog",
            name="n_logins",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Número de Inicios de Sesión"
            ),
        ),
        migrations.AddField(
            model_name="appactivitylog",
            name="time_in_app",
            field=models.IntegerField(
                blank=True,
                help_text="Tiempo total en la aplicación en segundos",
                null=True,
                verbose_name="Tiempo en la Aplicación (segundos)",
            ),
        ),
        migrations.AddField(
            model_name="appactivitylog",
            name="time_in_app_str",
            field=models.CharField(
                blank=True,
                help_text="Tiempo total en la aplicación en formato HH:MM:SS",
                max_length=255,
                null=True,
                verbose_name="Tiempo en la Aplicación (formato HH:MM:SS)",
            ),
        ),
    ]
