# Generated by Django 4.2.14 on 2025-07-01 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "prevcad",
            "0005_alter_appactivitylog_options_appactivitylog_n_logins_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadableContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512, verbose_name="Título")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="downloadable_content/", verbose_name="Archivo"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Contenido Descargable",
                "verbose_name_plural": "Contenidos Descargables",
                "ordering": ["-created_date"],
            },
        ),
        migrations.AlterField(
            model_name="appactivitylog",
            name="time_in_app_str",
            field=models.CharField(
                blank=True,
                help_text="Tiempo total en la aplicación",
                max_length=255,
                null=True,
                verbose_name="Tiempo en la Aplicación",
            ),
        ),
        migrations.CreateModel(
            name="DownloadByUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "download_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Descarga"
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prevcad.downloadablecontent",
                        verbose_name="Contenido Descargable",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Descarga por Usuario",
                "verbose_name_plural": "Descargas por Usuario",
                "ordering": ["-download_date"],
            },
        ),
        migrations.AddIndex(
            model_name="downloadablecontent",
            index=models.Index(fields=["title"], name="prevcad_dow_title_e5b829_idx"),
        ),
        migrations.AddIndex(
            model_name="downloadablecontent",
            index=models.Index(
                fields=["created_date"], name="prevcad_dow_created_3016df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="downloadbyuser",
            index=models.Index(fields=["user"], name="prevcad_dow_user_id_6ad5b1_idx"),
        ),
        migrations.AddIndex(
            model_name="downloadbyuser",
            index=models.Index(
                fields=["download_date"], name="prevcad_dow_downloa_dad4ee_idx"
            ),
        ),
    ]
