# Generated by Django 4.2.14 on 2025-07-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prevcad", "0006_downloadablecontent_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="downloadbyuser",
            constraint=models.UniqueConstraint(
                fields=("user", "content"),
                name="unique_user_content_download",
                violation_error_message="El usuario ya ha descargado este contenido.",
            ),
        ),
    ]
