# Generated by Django 4.2.14 on 2025-07-02 00:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("prevcad", "0007_downloadbyuser_unique_user_content_download"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadbyuser",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Fecha de Creación",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="downloadbyuser",
            name="downloaded",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el contenido ha sido descargado",
                verbose_name="Descargado",
            ),
        ),
        migrations.AddField(
            model_name="downloadbyuser",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de Actualización"
            ),
        ),
        migrations.AlterField(
            model_name="downloadbyuser",
            name="download_date",
            field=models.DateTimeField(blank=True, verbose_name="Fecha de Descarga"),
        ),
    ]
