# Generated by Django 4.2.14 on 2025-07-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prevcad", "0008_downloadbyuser_created_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloadbyuser",
            name="download_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Descarga"
            ),
        ),
    ]
