# Generated by Django 5.2.4 on 2025-07-09 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prevcad", "0009_alter_downloadbyuser_download_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512, verbose_name="Nombre")),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Categoría"
                    ),
                ),
                ("free_text", models.TextField(blank=True, verbose_name="Texto Libre")),
                (
                    "file",
                    models.FileField(
                        upload_to="system_documents/", verbose_name="Archivo"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Edición"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Editor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento del Sistema",
                "verbose_name_plural": "Documentos del Sistema",
                "ordering": ["-updated_date"],
                "indexes": [
                    models.Index(fields=["name"], name="prevcad_sys_name_ab4229_idx"),
                    models.Index(
                        fields=["updated_date"], name="prevcad_sys_updated_a01be0_idx"
                    ),
                ],
            },
        ),
    ]
